@startuml

actor "Enseignant" as User
participant "Interface" as UI
participant "Système" as System
participant "Base de Données" as DB

== 1. Ajout d'Étudiant ==
User -> UI : "Clique sur 'Ajouter Étudiant'"
activate UI
UI -> System : "Transmet les informations"
activate System
System -> DB : "Enregistre nouvel étudiant"
activate DB
DB --> System : "Confirmation d'enregistrement"
deactivate DB
System --> UI : "ID attribué"
deactivate System
UI --> User : "Affiche: 'Étudiant ajouté avec succès'"
deactivate UI

== 2. Modification l'étudiant ==
User -> UI : "Clique sur 'Modifier'"
activate UI
UI -> System : "Demande de modification"
activate System
System -> DB : "Vérifie existence étudiant"
activate DB
alt Existe
    DB --> System : "Données actuelles"
    System -> DB : "Mise à jour informations"
    DB --> System : "Confirmation"
    deactivate DB
    System --> UI : "Modification réussie"
    deactivate System
    UI --> User : "Affiche: 'Fiche mise à jour'"
else N'existe pas
    DB --> System : "Non trouvé"
    deactivate DB
    System --> UI : "Erreur"
    deactivate System
    UI --> User : "Affiche: 'Étudiant introuvable'"
end
deactivate UI

== 3. Suppression l'étudiant ==
User -> UI : "Clique sur 'Supprimer'"
activate UI
UI -> System : "Demande de suppression"
activate System
System -> DB : "Vérifie existence"
activate DB
alt Existe
    DB --> System : "Confirme existence"
    System -> DB : "Supprime l'étudiant"
    DB --> System : "Confirmation"
    deactivate DB
    System --> UI : "Suppression réussie"
    deactivate System
    UI --> User : "Affiche: 'Étudiant supprimé'"
else N'existe pas
    DB --> System : "Non trouvé"
    deactivate DB
    System --> UI : "Erreur"
    deactivate System
    UI --> User : "Affiche: 'Étudiant introuvable'"
end
deactivate UI

== 4. Liste des étudiants==
User -> UI : "Clique sur 'Liste Étudiants'"
activate UI
UI -> System : "Demande la liste"
activate System
System -> DB : "Récupère tous les étudiants"
activate DB
DB --> System : "Liste complète"
deactivate DB
System --> UI : "Données formatées"
deactivate System
UI --> User : "Affiche tableau clair des étudiants"
deactivate UI
@enduml